=== elgasilaban/sccddev/www/WEB-INF/classes/component-registry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
* Licensed Materials - Property of IBM
* Restricted Materials of IBM
* 5724-U18
* (C) COPYRIGHT IBM CORP. 2010 All Rights Reserved.
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with
* IBM Corp.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="component-registry">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="component-descriptor" />
			</xsd:sequence>
			<xsd:attribute name="package" type="xsd:string" />
			<xsd:attribute name="basedir" type="xsd:string" />
		</xsd:complexType>
		<xsd:unique name="component-descriptor-name-uniqueness">
			<xsd:selector xpath="component-descriptor"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:element name="component-descriptor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property-list" />
				<xsd:element ref="render-block" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="instance-class" type="xsd:string" />
			<xsd:attribute name="descriptor-class" type="xsd:string" />
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="render-block">
	</xsd:element>

	<xsd:element name="property-list">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="property" />
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="property-name-uniqueness">
			<xsd:selector xpath="property"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="property">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="flag" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="default-value" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
		<xsd:unique name="flag-name-uniqueness">
			<xsd:selector xpath="flag"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:element name="flag">
		<xsd:complexType>
			<xsd:attribute name="name" type="flag" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="flag">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="global"></xsd:enumeration>
			<xsd:enumeration value="system"></xsd:enumeration>
			<xsd:enumeration value="final"></xsd:enumeration>
			<xsd:enumeration value="translatable"></xsd:enumeration>
			<xsd:enumeration value="renderid"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="default-value" type="xsd:string" />

</xsd:schema>

=== elgasilaban/sccddev/properties/registry-extensions/map-component-registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * IBM Confidential
 *
 * OCO Source Materials
 *
 * 5724-U18
 *
 * (C) COPYRIGHT IBM CORP. 2011
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has been
 * deposited with the U.S. Copyright Office.
 *
 -->
<component-registry basedir="webclient\components"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='../component-registry.xsd'>    
	<component-descriptor name="mxmap" instance-class="com.ibm.tivoli.maximo.map.MapComponent">
		<property-list>			
			<property name="jsp-filename">
				<default-value>mxmap/map</default-value>
			</property>		
			<property name="id">
				<flag name="final" />
			</property>
			<property name="dataattribute" />

			<property name="inputmode" />
			
			<property name="alwaysinclude">
				<default-value>true</default-value>
			</property>
			<!-- Set defaultrender to false so we can update the component via 
			     javascript instead of DOM element replacement -->
			<property name="defaultrender">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<property name="visible">
				<default-value>true</default-value>
			</property>
			<property name="synchronous">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<!-- These two properties are need to get the component to stay synchronized with other components 
			   that are bound to the same data attribute -->
			<property name="inttype" />
			<property name="takesvalue">
				<default-value>true</default-value>
			</property>
			<property name="destroynotify">
				<default-value>true</default-value>
			</property>
			
		</property-list>
	</component-descriptor>
	<component-descriptor name="geocoderbutton">
		<property-list>
			<property name="jsp-filename">
				<default-value>mxmap/geocoderbutton</default-value>
			</property>
			<property name="advancedlongop">
				<default-value>false</default-value>
			</property>
			<property name="buttonsenabled" />
			<property name="id">
				<flag name="final" />
			</property>
			<property name="visible">
				<default-value>true</default-value>
			</property>
			<property name="disabled">
				<default-value>false</default-value>
			</property>
			<property name="image" />
			<property name="label" >
				<flag name="translatable" />
			</property>
			<property name="longopmessage" />
			<property name="mxeventjshandler" />
			<property name="addresstxtfld" />
			<property name="mxevent" />
			<property name="href" />
			<property name="cssclass" />
			<property name="textcss" />
			<property name="prepend" />			
			<property name="menutype" />
			<property name="default" />
			<property name="targetid" />
			<property name="takesfocus">
				<default-value>true</default-value>
			</property>
			<property name="clickablestate" />
			<property name="eventvalue" />
			<property name="linkedfocusid" />
			<property name="doclinkuploadbutton">
				<default-value>false</default-value>
			</property>
			<property name="hidewhen" />
			<property name="defaultrender">
				<flag name="final" />
				<default-value>true</default-value>
			</property>
			<property name="borderalways">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<property name="usefieldsizegroup" />
			<property name="width" />
			<property name="mxejsgeocodeaction" />
			<property name="mapControlId">
				<default-value>mxmap_div</default-value>
			</property>
			<property name="alwaysinclude">
				<default-value>true</default-value>
			</property>
		</property-list>
	</component-descriptor>
	
	<component-descriptor name="mxroute" instance-class="com.ibm.tivoli.maximo.map.RouteComponent">
		<property-list>
			
			<property name="advancedlongop">
				<default-value>false</default-value>
			</property>
			<property name="id">
				<flag name="final" />
			</property>
			<property name="visible">
				<default-value>true</default-value>
			</property>
			<property name="disabled">
				<default-value>false</default-value>
			</property>
			<property name="image" />
			<property name="label" >
				<flag name="translatable" />
			</property>
			<property name="mxevent" />
			
			<property name="cssclass" />
			<property name="default" />
			<property name="targetid" />
			<property name="takesfocus">
				<default-value>true</default-value>
			</property>
			<property name="eventvalue" />
			<property name="linkedfocusid" />
			<property name="doclinkuploadbutton">
				<default-value>false</default-value>
			</property>
			<property name="hidewhen" />
			<property name="defaultrender">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<property name="width" />
			<property name="textcss" />
			<property name="alwaysinclude">
				<default-value>false</default-value>
			</property>
			<property name="routecolor">
				<default-value>#1c29a8</default-value>
			</property>
		</property-list>
	</component-descriptor>	
	
	<component-descriptor name="mxdispatcher" instance-class="com.ibm.tivoli.maximo.map.dispatcher.MapDispatcherComponent">
		<property-list>
			<property name="jsp-filename">
				<default-value>mxmap/dispatcher</default-value>
			</property>
			<property name="advancedlongop">
				<default-value>true</default-value>
			</property>
			<property name="codebase" />
			<property name="classid" />
			<property name="code" />
			<property name="id">
				<flag name="final" />
			</property>
			<property name="visible">
				<default-value>true</default-value>
			</property>
			
			<property name="alwaysinclude">
				<default-value>true</default-value>
			</property>
			<property name="disabled">
				<default-value>false</default-value>
			</property>			
			<property name="mxevent" />			
			<property name="default" />
			<property name="targetid" />
			<property name="takesfocus">
				<default-value>false</default-value>
			</property>			
			<property name="doclinkuploadbutton">
				<default-value>false</default-value>
			</property>			
			<property name="defaultrender">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<property name="width" />
			<property name="textcss" />
			<property name="inttype" />
			<property name="mapControlId">
				<default-value>mxmap_div</default-value>
			</property>
			<property name="takesvalue">
				<default-value>true</default-value>
			</property>
			<property name="height">
				<default-value>400px</default-value>
			</property>
		</property-list>
	</component-descriptor>
	
	
	<component-descriptor name="lbsdatacollection" instance-class="com.ibm.tivoli.maximo.map.data.GpsDataCollectorComponent">
		<property-list>
			<property name="jsp-filename">
				<default-value>mxmap/gpsdatacollector</default-value>
			</property>
			<property name="advancedlongop">
				<default-value>true</default-value>
			</property>
			<property name="id">
				<flag name="final" />
			</property>
			<property name="visible">
				<default-value>true</default-value>
			</property>
			
			<property name="alwaysinclude">
				<default-value>true</default-value>
			</property>
			<property name="disabled">
				<default-value>false</default-value>
			</property>			
			<property name="mxevent" />			
			<property name="default" />
			<property name="targetid" />
			<property name="takesfocus">
				<default-value>false</default-value>
			</property>			
			<property name="doclinkuploadbutton">
				<default-value>false</default-value>
			</property>			
			<property name="defaultrender">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<property name="width" />
			<property name="textcss" />
			<property name="inttype" />
			<property name="takesvalue">
				<default-value>true</default-value>
			</property>
		</property-list>
	</component-descriptor>
	
</component-registry>

=== elgasilaban/sccddev/www/WEB-INF/classes/registry-extensions/skd-component-registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * IBM Confidential
 *
 * OCO Source Materials
 *
 * @CODETOBEDEFINED
 *
 * (C) COPYRIGHT IBM CORP. 2012
 *
 * The source code for this program is not published or otherwise
 * divested of its trade secrets, irrespective of what has been
 * deposited with the U.S. Copyright Office.
 *
 -->
<component-registry basedir="webclient/components"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation='../component-registry.xsd'>

	<component-descriptor name="asnviewer">
		<property-list>
			<property name="archive" />
			<property name="actiondatasrc" />
			<property name="classid" />
			<property name="code" />
			<property name="codebase" />
			<property name="dataattribute" />
			<property name="datasrc">
				<flag name="global" />
			</property>
			<property name="defaultrender">
				<default-value>false</default-value>
			</property>
			<property name="display">
				<flag name="global" />
				<default-value>true</default-value>
			</property>
			<property name="height" />
			<property name="id">
				<flag name="final" />
			</property>
			<property name="jsp-filename">
				<default-value>asnviewer</default-value>
			</property>
			<property name="label">
				<flag name="translatable" />
			</property>
			<property name="nodedatasrc" />
			<property name="textcss" />
			<property name="width" />
		</property-list>
	</component-descriptor>

	<component-descriptor name="skdviewer">
		<property-list>
			<property name="archive" />
			<property name="actiondatasrc" />
			<property name="classid" />
			<property name="code" />
			<property name="codebase" />
			<property name="dataattribute" />
			<property name="datasrc">
				<flag name="global" />
			</property>
			<property name="defaultrender">
				<default-value>false</default-value>
			</property>
			<property name="display">
				<flag name="global" />
				<default-value>true</default-value>
			</property>
			<property name="height" />
			<property name="id">
				<flag name="final" />
			</property>
			<property name="jsp-filename">
				<default-value>skdviewer</default-value>
			</property>
			<property name="label">
				<flag name="translatable" />
			</property>
			<property name="nodedatasrc" />
			<property name="textcss" />
			<property name="width" />
		</property-list>
	</component-descriptor>

</component-registry>
